# Refer to golangci-lint's example config file for more options and information:
# https://github.com/golangci/golangci-lint/blob/master/.golangci.reference.yml

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - goimports
    - govet
    - staticcheck
    - asciicheck
    - decorder
    - errname
    - exhaustive
    - copyloopvar
    - gosec
    - grouper
    - loggercheck
    - paralleltest
    - unconvert
    - whitespace

linters-settings:
  exhaustive:
    default-signifies-exhaustive: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0